---
# This playbook contains db plays that will run sql import.

- name: Copy sql dump
  copy:
    src: backup.sql
    dest: /home/deploy/square_check/backup.sql

- name: Import dump to database
  # Hardcode search docker container name db
  shell: cat backup.sql | docker exec -i $(docker ps -aqf "name=db") psql -U {{ DB_USERNAME }} {{ DB_DATABASE }}
  args:
    chdir: /home/deploy/square_check
